; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = examples

[env]
build_type = debug
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.35
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
build_flags = 
    -DUSE_ESP_IDF_LOG
;     -DCONFIG_LOG_DEFAULT_LEVEL=1
;     -DCONFIG_LOG_MAXIMUM_LEVEL=5
;     -DCONFIG_LOG_DYNAMIC_LEVEL_CONTROL=5
	
[env:debugging]
build_src_filter = -<*> +<Debugging> +<../src/*.cpp>

[env:duration]
build_src_filter = -<*> +<Duration> +<../src/*.cpp>

[env:boot]
build_src_filter = -<*> +<Boot> +<../src/*.cpp>

[env:executor_active]
build_src_filter = -<*> +<Executor/Active> +<../src/*.cpp>

[env:executor_light]
build_src_filter = -<*> +<Executor/Light> +<../src/*.cpp>

[env:executor_deep]
build_src_filter = -<*> +<Executor/Deep> +<../src/*.cpp>

[env:executor_mixed]
build_src_filter = -<*> +<Executor/Mixed> +<../src/*.cpp>

[env:executor_tick]
build_src_filter = -<*> +<Executor/Tick> +<../src/*.cpp>

[env:executor_demand]
build_src_filter = -<*> +<Executor/Demand> +<../src/*.cpp>

[env:executor_sleep_control]
build_src_filter = -<*> +<Executor/SleepControl> +<../src/*.cpp>

[env:state_simple]
build_src_filter = -<*> +<State/Simple> +<../src/*.cpp>

[env:state_save]
build_src_filter = -<*> +<State/SaveState> +<../src/*.cpp>

[env:state_reactive]
build_src_filter = -<*> +<State/Reactive> +<../src/*.cpp>

[env:state_sleep_modes]
build_src_filter = -<*> +<State/SleepModes> +<../src/*.cpp>

[env:pin_active_interrupt]
build_src_filter = -<*> +<Pin/ActiveInterrupt> +<../src/*.cpp>

[env:pin_active_interrupt_flash]
build_src_filter = -<*> +<Pin/ActiveInterruptFlash> +<../src/*.cpp>

[env:pin_light_sleep_interrupt]
build_src_filter = -<*> +<Pin/LightSleepInterrupt> +<../src/*.cpp>

[env:pin_deep_sleep_interrupt_pulldown]
build_src_filter = -<*> +<Pin/DeepSleepInterruptPullDown> +<../src/*.cpp>

[env:pin_deep_sleep_interrupt_pullup]
build_src_filter = -<*> +<Pin/DeepSleepInterruptPullUp> +<../src/*.cpp>

[env:pin_multi_sleep_interrupt]
build_src_filter = -<*> +<Pin/MultiSleepInterrupt> +<../src/*.cpp>

[env:pin_read]
build_src_filter = -<*> +<Pin/-ReadPin> +<../src/*.cpp>

[env:pin_write]
build_src_filter = -<*> +<Pin/-WritePin> +<../src/*.cpp>

[env:pin_tone]
build_src_filter = -<*> +<Pin/-Tone> +<../src/*.cpp>

[env:http_simple]
build_src_filter = -<*> +<HttpServer/Simple> +<../src/*.cpp>

[env:setting_simple]
build_src_filter = -<*> +<Setting/Simple> +<../src/*.cpp>

[env:executor_active_cancel]
build_src_filter = -<*> +<Executor/ActiveCancel> +<../src/*.cpp>