; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
src_dir = examples

[env]
build_type = debug
platform = https://github.com/pioarduino/platform-espressif32.git#develop
board = esp32dev
framework = arduino
monitor_filters = esp32_exception_decoder
monitor_speed = 115200
build_flags = 
    -DUSE_ESP_IDF_LOG
;     -DCONFIG_LOG_DEFAULT_LEVEL=1
;     -DCONFIG_LOG_MAXIMUM_LEVEL=5
;     -DCONFIG_LOG_DYNAMIC_LEVEL_CONTROL=5
	
[env:debugging]
build_src_filter = -<*> +<Debugging> +<../src/*.cpp>

[env:executor_active]
build_src_filter = -<*> +<executor/active> +<../src/*.cpp>

[env:executor_light]
build_src_filter = -<*> +<executor/light> +<../src/*.cpp>

[env:executor_deep]
build_src_filter = -<*> +<executor/deep> +<../src/*.cpp>

[env:executor_mixed]
build_src_filter = -<*> +<executor/mixed> +<../src/*.cpp>

[env:executor_tick]
build_src_filter = -<*> +<executor/tick> +<../src/*.cpp>

[env:executor_demand]
build_src_filter = -<*> +<executor/demand> +<../src/*.cpp>

[env:state_simple]
build_src_filter = -<*> +<state/simple> +<../src/*.cpp>

[env:state_save]
build_src_filter = -<*> +<state/savestate> +<../src/*.cpp>

[env:pin_active_interrupt]
build_src_filter = -<*> +<pin/ActiveInterrupt> +<../src/*.cpp>

[env:pin_light_sleep_interrupt]
build_src_filter = -<*> +<pin/LightSleepInterrupt> +<../src/*.cpp>

[env:pin_deep_sleep_interrupt]
build_src_filter = -<*> +<pin/DeepSleepInterrupt> +<../src/*.cpp>

[env:pin_multi_sleep_interrupt]
build_src_filter = -<*> +<pin/MultiSleepInterrupt> +<../src/*.cpp>

[env:pin_read]
build_src_filter = -<*> +<pin/ReadPin> +<../src/*.cpp>

[env:pin_write]
build_src_filter = -<*> +<pin/WritePin> +<../src/*.cpp>

[env:pin_tone]
build_src_filter = -<*> +<pin/Tone> +<../src/*.cpp>